name: Pull from PA thegraph public repo

on: 
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to pull from Perpetual-Altruism-Ltd/graph-node'
        required: true
        default: 'master'


jobs:
  createBranchAndPR:
    runs-on: self-hosted
    steps:

      - name: Install Github CLI
        run: |
          sudo apt update
          sudo apt install -y curl
          curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg
          sudo chmod go+r /usr/share/keyrings/githubcli-archive-keyring.gpg
          echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null
          sudo apt update
          sudo apt install -y gh

      - name: Cleanup
        run: rm -rf privateRepo

      - name: Checkout sources
        uses: actions/checkout@v2
        with:
          path: privateRepo   

      - name: Get back latest state from Perpetual-Altruism-Ltd/graph-node, branch ${{ github.event.inputs.branch }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd privateRepo
          git checkout ${{ github.event.inputs.branch }}
          git remote add public https://github.com/Perpetual-Altruism-Ltd/graph-node.git
          git fetch public
          git checkout -b ${{ github.event.inputs.branch }}-pullFromPublic public/${{ github.event.inputs.branch }}
          git push origin ${{ github.event.inputs.branch }}-pullFromPublic
          gh pr create --base ${{ github.event.inputs.branch }} --title "PR to merge upstream code from Perpetual-Altruism-Ltd/graph-node, branch ${{ github.event.inputs.branch }}" --body "..."